# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1078, 850)
        MainWindow.setMinimumSize(QtCore.QSize(840, 425))
        MainWindow.setMaximumSize(QtCore.QSize(1650, 850))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(840, 425))
        self.centralwidget.setMaximumSize(QtCore.QSize(1650, 850))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Gimg1_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.Gimg1_2.setFont(font)
        self.Gimg1_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Gimg1_2.setFlat(False)
        self.Gimg1_2.setObjectName("Gimg1_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Gimg1_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 501, 281))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Img1_Disp = ImageView(self.horizontalLayoutWidget)
        self.Img1_Disp.setObjectName("Img1_Disp")
        self.horizontalLayout.addWidget(self.Img1_Disp)
        spacerItem = QtWidgets.QSpacerItem(11, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Img1_CDisp = ImageView(self.horizontalLayoutWidget)
        self.Img1_CDisp.setObjectName("Img1_CDisp")
        self.horizontalLayout.addWidget(self.Img1_CDisp)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.Gimg1_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(230, 20, 281, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Upbtn1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Upbtn1.setFont(font)
        self.Upbtn1.setObjectName("Upbtn1")
        self.horizontalLayout_3.addWidget(self.Upbtn1)
        self.Img1_Comb = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.Img1_Comb.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Img1_Comb.setFont(font)
        self.Img1_Comb.setObjectName("Img1_Comb")
        self.Img1_Comb.addItem("")
        self.Img1_Comb.addItem("")
        self.Img1_Comb.addItem("")
        self.Img1_Comb.addItem("")
        self.Img1_Comb.addItem("")
        self.horizontalLayout_3.addWidget(self.Img1_Comb)
        self.verticalLayout.addWidget(self.Gimg1_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Gmix = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.Gmix.setFont(font)
        self.Gmix.setObjectName("Gmix")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Gmix)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 501, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(171, 0))
        self.label_5.setMaximumSize(QtCore.QSize(171, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Comp1_CombS = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.Comp1_CombS.setEnabled(True)
        self.Comp1_CombS.setMinimumSize(QtCore.QSize(0, 0))
        self.Comp1_CombS.setMaximumSize(QtCore.QSize(97, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Comp1_CombS.setFont(font)
        self.Comp1_CombS.setObjectName("Comp1_CombS")
        self.Comp1_CombS.addItem("")
        self.Comp1_CombS.addItem("")
        self.Comp1_CombS.addItem("")
        self.horizontalLayout_7.addWidget(self.Comp1_CombS)
        self.Slider1 = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.Slider1.setOrientation(QtCore.Qt.Horizontal)
        self.Slider1.setObjectName("Slider1")
        self.horizontalLayout_7.addWidget(self.Slider1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.Comp1C_CombS = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.Comp1C_CombS.setEnabled(True)
        self.Comp1C_CombS.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Comp1C_CombS.setFont(font)
        self.Comp1C_CombS.setObjectName("Comp1C_CombS")
        self.Comp1C_CombS.addItem("")
        self.Comp1C_CombS.addItem("")
        self.Comp1C_CombS.addItem("")
        self.Comp1C_CombS.addItem("")
        self.Comp1C_CombS.addItem("")
        self.Comp1C_CombS.addItem("")
        self.Comp1C_CombS.addItem("")
        self.verticalLayout_5.addWidget(self.Comp1C_CombS)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(171, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Comp2_CombS = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.Comp2_CombS.setEnabled(True)
        self.Comp2_CombS.setMinimumSize(QtCore.QSize(0, 0))
        self.Comp2_CombS.setMaximumSize(QtCore.QSize(97, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Comp2_CombS.setFont(font)
        self.Comp2_CombS.setObjectName("Comp2_CombS")
        self.Comp2_CombS.addItem("")
        self.Comp2_CombS.addItem("")
        self.Comp2_CombS.addItem("")
        self.horizontalLayout_9.addWidget(self.Comp2_CombS)
        self.Slider2 = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.Slider2.setOrientation(QtCore.Qt.Horizontal)
        self.Slider2.setObjectName("Slider2")
        self.horizontalLayout_9.addWidget(self.Slider2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.Comp2C_CombS = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.Comp2C_CombS.setEnabled(True)
        self.Comp2C_CombS.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Comp2C_CombS.setFont(font)
        self.Comp2C_CombS.setObjectName("Comp2C_CombS")
        self.Comp2C_CombS.addItem("")
        self.Comp2C_CombS.addItem("")
        self.Comp2C_CombS.addItem("")
        self.Comp2C_CombS.addItem("")
        self.Comp2C_CombS.addItem("")
        self.Comp2C_CombS.addItem("")
        self.Comp2C_CombS.addItem("")
        self.verticalLayout_6.addWidget(self.Comp2C_CombS)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.Gmix)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(220, 40, 291, 51))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label.setMaximumSize(QtCore.QSize(111, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.Output_Comb = QtWidgets.QComboBox(self.horizontalLayoutWidget_7)
        self.Output_Comb.setEnabled(True)
        self.Output_Comb.setMinimumSize(QtCore.QSize(0, 0))
        self.Output_Comb.setMaximumSize(QtCore.QSize(97, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Output_Comb.setFont(font)
        self.Output_Comb.setObjectName("Output_Comb")
        self.Output_Comb.addItem("")
        self.Output_Comb.addItem("")
        self.Output_Comb.addItem("")
        self.horizontalLayout_10.addWidget(self.Output_Comb)
        self.gridLayout_3.addWidget(self.Gmix, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Gimg1 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.Gimg1.setFont(font)
        self.Gimg1.setObjectName("Gimg1")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.Gimg1)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(230, 20, 281, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Upbtn2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Upbtn2.setFont(font)
        self.Upbtn2.setObjectName("Upbtn2")
        self.horizontalLayout_4.addWidget(self.Upbtn2)
        self.Img1_Comb_2 = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        self.Img1_Comb_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Img1_Comb_2.setFont(font)
        self.Img1_Comb_2.setObjectName("Img1_Comb_2")
        self.Img1_Comb_2.addItem("")
        self.Img1_Comb_2.addItem("")
        self.Img1_Comb_2.addItem("")
        self.Img1_Comb_2.addItem("")
        self.Img1_Comb_2.addItem("")
        self.horizontalLayout_4.addWidget(self.Img1_Comb_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.Gimg1)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 80, 501, 281))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Img2_Disp = ImageView(self.horizontalLayoutWidget_2)
        self.Img2_Disp.setObjectName("Img2_Disp")
        self.horizontalLayout_2.addWidget(self.Img2_Disp)
        spacerItem2 = QtWidgets.QSpacerItem(11, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.Img2_CDisp = ImageView(self.horizontalLayoutWidget_2)
        self.Img2_CDisp.setObjectName("Img2_CDisp")
        self.horizontalLayout_2.addWidget(self.Img2_CDisp)
        self.verticalLayout_3.addWidget(self.Gimg1)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Gout = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(27)
        self.Gout.setFont(font)
        self.Gout.setObjectName("Gout")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.Gout)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 80, 501, 281))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Out1 = ImageView(self.horizontalLayoutWidget_5)
        self.Out1.setObjectName("Out1")
        self.horizontalLayout_8.addWidget(self.Out1)
        spacerItem3 = QtWidgets.QSpacerItem(11, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.Out2 = ImageView(self.horizontalLayoutWidget_5)
        self.Out2.setObjectName("Out2")
        self.horizontalLayout_8.addWidget(self.Out2)
        self.verticalLayout_4.addWidget(self.Gout)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1078, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Gimg1_2.setTitle(_translate("MainWindow", "First Image"))
        self.Upbtn1.setText(_translate("MainWindow", "Upload Image"))
        self.Img1_Comb.setItemText(0, _translate("MainWindow", "Select Component"))
        self.Img1_Comb.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.Img1_Comb.setItemText(2, _translate("MainWindow", "Phase"))
        self.Img1_Comb.setItemText(3, _translate("MainWindow", "Real"))
        self.Img1_Comb.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.Gmix.setTitle(_translate("MainWindow", "Mixer"))
        self.label_5.setText(_translate("MainWindow", "First Component:"))
        self.Comp1_CombS.setItemText(0, _translate("MainWindow", "Select Image"))
        self.Comp1_CombS.setItemText(1, _translate("MainWindow", "First Image"))
        self.Comp1_CombS.setItemText(2, _translate("MainWindow", "Second Image"))
        self.Comp1C_CombS.setItemText(0, _translate("MainWindow", "Select Component"))
        self.Comp1C_CombS.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.Comp1C_CombS.setItemText(2, _translate("MainWindow", "Phase"))
        self.Comp1C_CombS.setItemText(3, _translate("MainWindow", "Real"))
        self.Comp1C_CombS.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.Comp1C_CombS.setItemText(5, _translate("MainWindow", "Uniform Magnitude"))
        self.Comp1C_CombS.setItemText(6, _translate("MainWindow", "Uniform Phase"))
        self.label_6.setText(_translate("MainWindow", "Second Compnent:"))
        self.Comp2_CombS.setItemText(0, _translate("MainWindow", "Select Image"))
        self.Comp2_CombS.setItemText(1, _translate("MainWindow", "First Image"))
        self.Comp2_CombS.setItemText(2, _translate("MainWindow", "Second Image"))
        self.Comp2C_CombS.setItemText(0, _translate("MainWindow", "Select Component"))
        self.Comp2C_CombS.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.Comp2C_CombS.setItemText(2, _translate("MainWindow", "Phase"))
        self.Comp2C_CombS.setItemText(3, _translate("MainWindow", "Real"))
        self.Comp2C_CombS.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.Comp2C_CombS.setItemText(5, _translate("MainWindow", "Uniform Magnitude"))
        self.Comp2C_CombS.setItemText(6, _translate("MainWindow", "Uniform Phase"))
        self.label.setText(_translate("MainWindow", "Display On:"))
        self.Output_Comb.setItemText(0, _translate("MainWindow", "Select Display"))
        self.Output_Comb.setItemText(1, _translate("MainWindow", "Output 1"))
        self.Output_Comb.setItemText(2, _translate("MainWindow", "Output 2"))
        self.Gimg1.setTitle(_translate("MainWindow", "Second Image"))
        self.Upbtn2.setText(_translate("MainWindow", "Upload Image"))
        self.Img1_Comb_2.setItemText(0, _translate("MainWindow", "Select Component"))
        self.Img1_Comb_2.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.Img1_Comb_2.setItemText(2, _translate("MainWindow", "Phase"))
        self.Img1_Comb_2.setItemText(3, _translate("MainWindow", "Real"))
        self.Img1_Comb_2.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.Gout.setTitle(_translate("MainWindow", "Output"))
from pyqtgraph import ImageView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
